### ISSUE TITLE
GPU memory

### ISSUE THREAD

**Issue by AmingWu** [daveredrum/ScanRefer#1]
Dear author:

Could I use one 1080ti with 12GB memory to reproduce your method? And how long does your model need to train?

**Comment by daveredrum** [comment]
Hi Aming

Sure, a 1080Ti with 12GB RAM is completely capable of reproducing our results. In our experiments, it took ~24 hours for the model (with RGB values) to converge on a 2080Ti.

Best
Dave

**Comment by AmingWu** [comment]
Thank you very much. I have filled the dataset form and sent to you.
