### ISSUE TITLE
Cannot reproduce the detection results

### ISSUE THREAD

**Issue by CurryYuan** [daveredrum/ScanRefer#11]
Hi, zhenyu,

Thanks for your wonderful work. However, I got a question when running your code.

Firstly, I train a model from scratch with the command `python script/train.py --use_color`. Then I test the model use script/eval.py. I can reproduce the grouding result, but the detection mAP is 23.67 . While this result in your paper Supplementary Material Table 8 [h] is 29.91. The difference is quite large.

I also test with the pre-trained model provided by VoteNet [repo](https://github.com/facebookresearch/votenet), which is 28.57. It is lower than Table 8 [a] 30.08, too. But this difference is much smaller.

Can you check this problem? It can be of great help.

**Comment by daveredrum** [comment]
Hi @CurryYuan,

Thanks a lot for letting me know the issue! Can you try to train the model without the reference branch and check if the problem persists? Also, please note that there's minor differences between our pipeline and the original VoteNet, since we modified the PointNet++ backbone implementation a bit. So don't forget to compile the PointNet++ backbone modules properly. :) 

Best
Dave

**Comment by CurryYuan** [comment]
Hi @daveredrum ,

If I train the model with --no_reference tag, the result is even worse. 

For testing the votenet pretrained model, I only change the proposal_module, backbone_module seems the same as votenet.

**Comment by daveredrum** [comment]
Can you try with `--no_reference --epoch 200`? Training only on the subset of ScanNet for 50 epochs by default could lead to bad performance. As for the VoteNet, we changed the PointNet++ backbone implementation, i.e. the C++/CUDA kernal of PointNet++ layer functions. Therefore, the detailed implementation is not necessarily the same as the original.

**Comment by CurryYuan** [comment]
The detection mAP is 23.38 when training with `--no_reference --epoch 200`.

**Comment by daveredrum** [comment]
This seems a bit different from the results I had one year ago - They should be similar with VoteNet in this setting. I'll look into this issue. Thanks for pointing out!
