### ISSUE TITLE
"Unique" subset for validation

### ISSUE THREAD

**Issue by metro-smiles** [daveredrum/ScanRefer#15]
Hi @daveredrum ,

Hope you are doing fine.

Great work! So I was wondering how do I know which samples fall in the "unique" split and which falls in the "multiple" one, as suggested in the Table 5 for example?

Would appreciate any pointers.

~Cheers!

**Comment by daveredrum** [comment]
Hi @metro-smiles, the objects whose semantic labels are unique in the scene will be dumped into "Unique" subset, while others will be "Multiple". The related explanation is located in Sec. 6.2.

**Comment by metro-smiles** [comment]
So @daveredrum , 

Really appreciate that! But do you have a split in the dataset release which identifies which queries refer to "unique" scenes and which ones don't?

**Comment by daveredrum** [comment]
No, it's not in the dataset release, but it can be computed on the fly during evaluation. Please check `scripts/eval.py` for more info.
