### ISSUE TITLE
The scene and the predicted boxes are unaligned

### ISSUE THREAD

**Issue by YasmeenAlsaedy** [daveredrum/ScanRefer#18]
Hi all,
We tried to visualize the boxes and the sense together using the open3d package. We first generated all the ply boxes by running the predict function and then we took the scene ply file ( scene0011_00_vh_clean_2.ply ).

Please check the below image.
<img width="723" alt="Screen Shot 2022-07-22 at 2 08 05 PM" src="https://user-images.githubusercontent.com/26979493/180427944-d3c0748f-4005-46fc-a0cf-66bb8a15649c.png">

**Comment by daveredrum** [comment]
Hi @YasmeenAlsaedy,

Thanks for your interest in our project! I'm wondering if you're using the original mesh files from ScanNet? All scene data and object boxes are axis-aligned during preprocessing (see [here](https://github.com/daveredrum/ScanRefer/blob/master/data/scannet/load_scannet_data.py#L65)). Please make sure you also use the same axis-aligned meshes for visualization.

**Comment by YasmeenAlsaedy** [comment]
Hi Dave,
Thank you for your prompt response! 
I was wondering what is the purpose of making the points axis-aligned in the preprocessing stage?

**Comment by daveredrum** [comment]
It's a standard preprocessing step used in many other projects, e.g. [VoteNet](https://github.com/facebookresearch/votenet), [3DETR](https://github.com/facebookresearch/3detr). Aligning the scenes to the axes and making them zero-centered can make the model generalize better, I guess.

**Comment by YasmeenAlsaedy** [comment]
Thank you so much for all your help!
