### ISSUE TITLE
Data Prepare

### ISSUE THREAD

**Issue by AmingWu** [daveredrum/ScanRefer#2]
Hello,

I have filled the form and sent to you. Have you received my filled dataset form?

Thank you

**Comment by daveredrum** [comment]
Yes and replied. :)

**Comment by ayushjain1144** [comment]
Hi daveredrum,

My group had applied for accessing the dataset a couple of weeks ago. I have reapplied again. Can you please look into it and provide access as soon as possible.

Thank you so much!

**Comment by wffancy** [comment]
Hi @daveredrum , 

I had also filled the form weeks before. Could you please look into it and give me some replies. Thanks!
