### ISSUE TITLE
About the multiview images selection.

### ISSUE THREAD

**Issue by Hiusam** [daveredrum/ScanRefer#21]
Hi Dave,

Thank you for your great work. I noticed that you used the ScanNet images from Ji Hou's 3DSIS for multiview feature. 

The original paper says, "we use 5 RGB images for each training chunk (with image selection based on average 3D instance coverage)." I want to ask do these images cover the whole scene. Or do these images cover all the objects mentioned in the language utterance so that based on the images, the target object can be identified? Do you have some analysis of these images?

I want to do the task in a RGB-D-only setting. Do you have any idea of the frames needed for the task? Thank you for your answer. 

#6

**Comment by daveredrum** [comment]
Hi @Hiusam, we used the sampled frames from 3D-SIS, i.e. every 20th frame from the ScanNet RGB-D video sequence. Hence, those frames should have a fair coverage over the whole scene. There's no such object-centric frame sampling scheme.

**Comment by Hiusam** [comment]
OK, thank you very much for your reply.
