### ISSUE TITLE
Input Dimension

### ISSUE THREAD

**Issue by AmingWu** [daveredrum/ScanRefer#5]
Dear author,

When I run python scripts/train.py --use_color, the dimension of data_dict['point_clouds'] is torch.Size([8, 40000, 7]). Why is the dimension not torch.Size([8, 40000, 6])?

**Comment by daveredrum** [comment]
Hi @AmingWu,

As the input feature, we also compute the height of each point to the ground surface. Therefore, the input size is 3 (xyz) + 3 (rgb) + 1 (height) = 7.

Best
Dave
