### ISSUE TITLE
Camera viewpoint correspondence to the object description

### ISSUE THREAD

**Issue by ayushjain1144** [daveredrum/ScanRefer#6]
Hi Dave,

I was wondering if there is a linkage between scanrefer reference query and a camera viewpoint for answering the question. For example, if the query is "there is a fridge to the left of bed", then is this query attached to a particular camera viewpoint which has fridge and bed and thus the query can be grounded? Are the questions linked to the camera viewpoint in some way? Or is there a way to find that viewpoint easily?

To give you the context, our work is based on rgbds, so at test time our model expects an RGB-D image from the relevant camera viewpoint and the query which needs to be answered.

Thank you

**Comment by cheng052** [comment]
Similar question! I also wonder how the viewpoint correspondence to the referring expression?

**Comment by Hiusam** [comment]
Same question!

**Comment by daveredrum** [comment]
Hi @ayushjain1144 @cheng052 @Hiusam, we've released the annotated viewpoints - Please check it out [here](https://github.com/daveredrum/ScanRefer/blob/master/README.md#star2-annotated-viewpoints-star2). Have fun playing around the viewpoints! :)

**Comment by Hiusam** [comment]
Great! Thank you, @daveredrum.
